config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :tags, only: [:index]
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments
  has_many :favorites
  
  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}
  validates :star, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :body, presence: true
end

app/models/dm.rb
class Dm < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :reciever, class_name: "User", foreign_key: "receiver_id"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
    has_one_attached :image

    has_many :group_users, dependent: :destroy
    has_many :users, through: :group_users, source: :user

    belongs_to :connection, class_name: "GroupUser", foreign_key: "owner_id"
    has_one :owner, through: :connection, source: :user

    def get_group_image(weight, height)
        unless self.image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        self.image.variant(resize_to_fill: [weight,height]).processed
    end
end

app/models/group_mail.rb
class GroupMail < ApplicationRecord
  belongs_to :group
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :user
    belongs_to :group
    validates_uniqueness_of :group_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # class_name: "User"でUserモデルを参照
  # belongs_to :user　と指定すると、どっちがどっちのuserかわからなくなる
  # follower, followedで分ける
  # しかし、そのままだとfollower, followedテーブルを探しに行くので、
  # class_name: "User"とすることで、userテーブルからデータを取ってくるようにする。
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # class_name: どのテーブルを参照するのか設定
  #　foreign_key: 参照する外部キー(カラム)を指定
  # through: 経由するテーブル
  # source: 参照するカラム

  # フォローされている人
  # Relationshipモデルに対して、followed_idを見てreverse_of_relationshipsという名前でアソシエーション
  # foreign_key(FK)には、@user.xxxとした際に「@user.idがfollower_idかfollowed_idなのか」を指定
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローされている人の情報が欲しい => フォローしている人の情報を取得
  # reverse_of_relationshipsを経由し、follower(belongs_toのやつ)カラムに対してfollowersという名前でアソシエーション
  # そのユーザーがフォローしている人orフォローされている人の一覧を出したい
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしている人
  # Relationshipモデルに対して、followed_idを見てrelationshipsという名前でアソシエーション
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローしている人の情報が欲しい => フォローされている人の情報を取得
  # relationshipsを経由し、followed(belongs_toのやつ)カラムに対してfollowingsという名前でアソシエーション
  has_many :followings, through: :relationships, source: :followed

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, source: :group

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # userはフォローされる人
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  # userはフォローをはずされるひと
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  # フォローしてるか確認したい人.followings?(フォローされているか確認したい人)
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(weight, height)
    unless self.profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    self.profile_image.variant(resize_to_fill: [weight,height]).processed
  end
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
    belongs_to :book
end

app/controllers/dm_controller.rb
class DmController < ApplicationController
	def index
		@new_message = Dm.new
		@user = User.find(params[:user_id])
		@sent_messages = Dm.where(sender_id: current_user.id, receiver_id: @user.id)
		@received_messages = Dm.where(receiver_id: current_user.id, sender_id: @user.id)
		@all_messages = (@sent_messages + @received_messages).uniq.sort_by(&:created_at)
	  end
	
	  def create
		@new_message = Dm.new(str_params)
		@new_message.sender_id = current_user.id
		@new_message.receiver_id = params[:user_id]
		@new_message.save!
		redirect_to user_dm_index_path(@new_message.receiver_id)
	  end
	
	
	  private
	  def str_params
		params.require(:dm).permit(:message)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dm_helper.rb
module DmHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_mails_helper.rb
module GroupMailsHelper
end

app/helpers/group_user_helper.rb
module GroupUserHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80,80) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
<!--          自分じゃなかったら-->
          <% unless current_user.id == user.id %>
<!--            フォローしてたら-->
            <% if current_user.following?(user) %>
              <%= link_to "フォローをはずす", user_relationships_path(user), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user), method: :create %>
            <% end %>
          <% end %>
        </td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <td><%= user.name %></td>
  </tr>
  <tr>
	  <th>introduction</th>
	  <td><%= user.introduction %></td>
  </tr>
  <tr>
    <th>follows</th>
    <td><%= link_to user.followings.count, user_followings_path(user) %></td>
  </tr>
  <tr>
    <th>followers</th>
    <td><%= link_to user.followers.count, user_followers_path(user) %></td>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォローをはずす", user_relationships_path(user), method: :delete, class: "btn btn-info" %>
      <% if user.following?(current_user)%>
        <%= link_to "chatを始める", user_dm_index_path(user) %>
      <% end %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user), method: :create, class: "btn btn-info" %>
    <% end %>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_posts_num.html.erb
<h2>検索結果</h2>
<table class='table'>
    <tr>
        <th>投稿数</th>
    </tr>
    <tr>
        <td><%= cnt %></td>
    </tr>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'info', user: current_user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
        </div>
        <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <p>
            <%= link_to "グループを作成する", new_user_group_path(current_user.id) %>
            |
            <%= link_to "グループ一覧", user_groups_path(current_user.id) %>
            </p>
        <%= render 'index',users: @users %>
        </div>
    </div>
</div>

app/views/users/print_posts_num_of_day.js.erb
$('#posts_amount').html("<%= j(render 'users/posts_num', cnt: @posts_book_cnt) %>")

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>

      <% if current_user == @user %>
        <div>
          <h2>投稿数の前日比・前週比</h2>
          <table class='table'>
            <tr>
              <th>今日の投稿数</th>
              <th>前日の投稿数</th>
              <th>前日比</th>
            </tr>
            <tr>
              <td>
                <%= @user.create_books_today %>
              </td>
              <td>
                <%= @user.create_books_yesterday %>
              </td>
              <td>
                <% unless @user.create_books_yesterday == 0 %>
                  <%= @user.create_books_today / @user.create_books_yesterday * 100 %>%
                <% else %>
                  昨日の投稿はありませんでした
                <% end %>
              </td>
            </tr>
          </table>

          <table class='table'>
            <tr>
              <th>今週の投稿数</th>
              <th>前週の投稿数</th>
              <th>前週比</th>
            </tr>
            <tr>
              <td>
                <%= @user.create_books_thisweek %>
              </td>
              <td>
                <%= @user.create_books_lastweek %>
              </td>
              <td>
                <% unless @user.create_books_lastweek == 0 %>
                  <%= @user.create_books_thisweek / @user.create_books_lastweek * 100%>%
                <% else %>
                  先週の投稿はありませんでした
                <% end %>
              </td>
            </tr>
          </table>

          <div>
            <h2>７日間分の投稿数</h2>
            <table>
              <tr>
                <th>6日前</th>
                <th>5日前</th>
                <th>4日前</th>
                <th>3日前</th>
                <th>2日前</th>
                <th>1日前</th>
                <th>今日</th>
              </tr>
              <tr>
                <% @user.number_of_posts_per_week.each do |post_num| %>
                  <td>
                    <%= post_num %>
                  </td>
                <% end %>
              </tr>
            </table>
          </div>
        </div>
      <% end %>
      <%# グラフの記述位置を設定 %>
      <div>
        <canvas id="mychart" data-turbolinks='false'></canvas>
      </div>
      <%# Chart.jsをCDNから含める %>
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      
      <div>
        <%= form_with local: false, url: users_posts_num_path, method: :get do |form| %>
          <%= form.date_field :day %>
          <%= form.submit "検索" %>
        <% end %>
      </div>
      <div id='posts_amount'>

      </div>
    </div>
  </div>
</div>

<script>
  var ctx = document.getElementById('mychart');
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
        datasets: [{
            label: '1週間の投稿数',
            data: <%= @user.number_of_posts_per_week %>,
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                min: 0,
                max: 10,
                ticks: {
                  stepSize: 1
                }
            }
        }
    }
  });
</script>

app/views/users/test.html.erb
<h1>ショッピングカート</h1>
<%= link_to "カートを空にする",cart_items_destroy_all_path,method: :delete %>
<table>
  <thead>
    <tr>
      <td>商品名</td>
      <td>単価（税込）</td>
      <td>数量</td>
      <td>小計</td>
      <td></td>
    </tr>
  </thead>
  <% @cart_item.each do |cart_item| %>
  <%= @total=@total+cart_item.subtotal %>
  <tr>
  <td><%= cart_item.item.name %></td>
  <td><%= cart_item.item.price * 1.1 %></td>
  <%= form_with model: cart_item, cart_item_path(cart_item.id), method: :patch do |f| %>
  <td><%= f.select :amount, *[1..10] %></td>
  <td><%= f.submit "変更" %></td>
  <% end %>
  <td><%= cart_item.amount %></td>
  <td><%= cart_item.item.price * 1.1 *cart_item.amount %></td>
  <td><%= link_to "削除する",cart_item_path(cart_item.id),method: :delete %></td>
  </tr>
  <% end %>
</table>
<%= button_to "買い物を続ける",root_path,method: :get %>
<tr>
  <td>合計金額</td>
  <td>¥<% @total %></td>
</tr>
<%= button_to "情報入力に進む",new_order_path,method: :get %>