config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :tags, only: [:index]
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments
  has_many :favorites
  
  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}
  validates :star, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :body, presence: true
end

app/models/dm.rb
class Dm < ApplicationRecord
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :reciever, class_name: "User", foreign_key: "receiver_id"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
    has_one_attached :image

    has_many :group_users, dependent: :destroy
    has_many :users, through: :group_users, source: :user

    belongs_to :connection, class_name: "GroupUser", foreign_key: "owner_id"
    has_one :owner, through: :connection, source: :user

    def get_group_image(weight, height)
        unless self.image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        self.image.variant(resize_to_fill: [weight,height]).processed
    end
end

app/models/group_mail.rb
class GroupMail < ApplicationRecord
  belongs_to :group
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
    belongs_to :user
    belongs_to :group
    validates_uniqueness_of :group_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # class_name: "User"でUserモデルを参照
  # belongs_to :user　と指定すると、どっちがどっちのuserかわからなくなる
  # follower, followedで分ける
  # しかし、そのままだとfollower, followedテーブルを探しに行くので、
  # class_name: "User"とすることで、userテーブルからデータを取ってくるようにする。
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # class_name: どのテーブルを参照するのか設定
  #　foreign_key: 参照する外部キー(カラム)を指定
  # through: 経由するテーブル
  # source: 参照するカラム

  # フォローされている人
  # Relationshipモデルに対して、followed_idを見てreverse_of_relationshipsという名前でアソシエーション
  # foreign_key(FK)には、@user.xxxとした際に「@user.idがfollower_idかfollowed_idなのか」を指定
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローされている人の情報が欲しい => フォローしている人の情報を取得
  # reverse_of_relationshipsを経由し、follower(belongs_toのやつ)カラムに対してfollowersという名前でアソシエーション
  # そのユーザーがフォローしている人orフォローされている人の一覧を出したい
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしている人
  # Relationshipモデルに対して、followed_idを見てrelationshipsという名前でアソシエーション
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローしている人の情報が欲しい => フォローされている人の情報を取得
  # relationshipsを経由し、followed(belongs_toのやつ)カラムに対してfollowingsという名前でアソシエーション
  has_many :followings, through: :relationships, source: :followed

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, source: :group

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  # userはフォローされる人
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  # userはフォローをはずされるひと
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  # フォローしてるか確認したい人.followings?(フォローされているか確認したい人)
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(weight, height)
    unless self.profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    self.profile_image.variant(resize_to_fill: [weight,height]).processed
  end
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
    belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    if params[:sort] == "0"
      @books = Book.all.order(created_at: :DESC)
    elsif params[:sort] == "1"
      @books = Book.all.order(star: :DESC)
    else
      @books = Book.all
    end
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :tag)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/dm_controller.rb
class DmController < ApplicationController
	def index
		@new_message = Dm.new
		@user = User.find(params[:user_id])
		@sent_messages = Dm.where(sender_id: current_user.id, receiver_id: @user.id)
		@received_messages = Dm.where(receiver_id: current_user.id, sender_id: @user.id)
		@all_messages = (@sent_messages + @received_messages).uniq.sort_by(&:created_at)
	  end
	
	  def create
		@new_message = Dm.new(str_params)
		@new_message.sender_id = current_user.id
		@new_message.receiver_id = params[:user_id]
		@new_message.save!
		redirect_to user_dm_index_path(@new_message.receiver_id)
	  end
	
	
	  private
	  def str_params
		params.require(:dm).permit(:message)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dm_helper.rb
module DmHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_mails_helper.rb
module GroupMailsHelper
end

app/helpers/group_user_helper.rb
module GroupUserHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form_group">
    <%= f.label :tag %>
    <%= f.text_field :tag, class: 'form-control book_tag' %>
  </div>
  <div class="form-group position-static">
    <p>評価:</P>
    <div id="post_raty"></div>
    <% if book.id.nil? %>
      <script>
          var elem = document.querySelector('#post_raty');
          var opt = {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              scoreName: 'book[star]',
          };
          raty(elem,opt);
      </script>
    <% else %>
      <%= render "output_star", book: book %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.tag, tags_path(tag: book.tag) %></td>
        <td class=<%= "favorite-" + book.id.to_s %> >
            <%= render "favorites/btn", book: book %>
        </td>
        <td><%= render "book_comments/counter", book: book %></td>
        <td width="170">
          <%= render "books/output_star", book: book %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_output_star.html.erb
<div id="show_star-<%= book.id %>"></div>
<script>
    var elem = document.querySelector('#show_star-<%= book.id %>');
    var opt = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        readOnly: true,
        score: <%= book.star %>
    };
    raty(elem,opt);
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= form_with url: tags_path, method: :get do |f| %>
  <%= f.text_field :tag %>
  <%= f.submit "タグ検索" %>
<% end %>
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 0), remote: true %>
      |
      <%= link_to "評価の高い順", books_path(sort: 1), remote: true %>
      <div id="index_table">
        <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/index.js.erb
$('#index_table').html("<%= j(render 'books/index',  books: @books ) %>")

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(80,80) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.tag, tags_path(tag: @book.tag) %></td>
          <td class=<%= "favorite-" + @book.id.to_s %> >
            <%= render "favorites/btn", book: @book %>
          </td>
          <td class="book-comments-counter">
            <%= render "book_comments/counter", book: @book %>
          </td>
          <td width="170"><%= render "output_star", book: @book %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %></td>
          <% end %>
        </tr>
      </table>
      
      <div class="book-comments-index">
        <%= render "book_comments/index", book: @book %>
      </div>
      <%= render "book_comments/form", book: @book, book_comment: @book_comment %>

    </div>
  </div>
</div>